#pragma once

#include <zephyr/sys/util.h>

#include <zephyr/usb/usb_device.h>
#include <zephyr/usb/class/usb_hid.h>

#define K_KEYBOARD 0x0000
#define K_CONSUMER 0x1000
#define K_FN 0x2000
#define K_SPECIAL 0x3000
#define K_TAP_HOLD 0xE000

#define HID_KEY_LCTRL (K_KEYBOARD | 0xE0)
#define HID_KEY_LSHIFT (K_KEYBOARD | 0xE1)
#define HID_KEY_LALT (K_KEYBOARD | 0xE2)
#define HID_KEY_LGUI (K_KEYBOARD | 0xE3)
#define HID_KEY_RCTRL (K_KEYBOARD | 0xE4)
#define HID_KEY_RSHIFT (K_KEYBOARD | 0xE5)
#define HID_KEY_RALT (K_KEYBOARD | 0xE6)
#define HID_KEY_RGUI (K_KEYBOARD | 0xE7)

#define HID_KEY_NONE 0
#define HID_KEY_NUBS 0x64
#define HID_KEY_VOLUME_UP (K_CONSUMER | 0xE9)
#define HID_KEY_VOLUME_DOWN (K_CONSUMER | 0xEA)
#define HID_KEY_MUTE (K_CONSUMER | 0xE2)
#define HID_KEY_PLAY_PAUSE (K_CONSUMER | 0xCD)
#define HID_KEY_NEXT_TRACK (K_CONSUMER | 0xB5)
#define HID_KEY_PREV_TRACK (K_CONSUMER | 0xB6)
#define HID_KEY_STOP (K_CONSUMER | 0xB7)
#define HID_KEY_EJECT (K_CONSUMER | 0xB8)
#define HID_KEY_SLEEP (K_CONSUMER | 0x32)

#define HID_KEY_TRANS (K_SPECIAL | 0x01)

#define BMK_HID_REPORT_ID_KEYBOARD 0x01
#define BMK_HID_REPORT_ID_CONSUMER 0x02
#define BMK_HID_REPORT_ID_LEDS 0x01

#define HID_USAGE_GD_KEYBOARD (0x06)
#define HID_USAGE_KEY (0x07)
#define HID_USAGE_LED (0x08)
#define HID_USAGE_CONSUMER (0x0C)
#define HID_USAGE_KEY_KEYBOARD_LEFTCONTROL (0xE0)
#define HID_USAGE_KEY_KEYBOARD_RIGHT_GUI (0xE7)
#define HID_USAGE_LED_NUM_LOCK (0x01)
#define HID_USAGE_LED_KANA (0x05)
#define HID_USAGE_CONSUMER_CONSUMER_CONTROL (0x01)

#define FN_MO(layer) (0x2100 | (layer & 0xFF))
#define FN_TO(layer) (0x2200 | (layer & 0xFF))
#define TH_LCTRL(key) (0xE000 | (key & 0xFF))
#define TH_LSHIFT(key) (0xE100 | (key & 0xFF))
#define TH_LALT(key) (0xE200 | (key & 0xFF))
#define TH_LGUI(key) (0xE300 | (key & 0xFF))
#define TH_RCTRL(key) (0xE400 | (key & 0xFF))
#define TH_RSHIFT(key) (0xE500 | (key & 0xFF))
#define TH_RALT(key) (0xE600 | (key & 0xFF))
#define TH_RGUI(key) (0xE700 | (key & 0xFF))

#define BMK_HID_MAIN_VAL_DATA (0x00 << 0)
#define BMK_HID_MAIN_VAL_VAR (0x01 << 1)
#define BMK_HID_MAIN_VAL_ABS (0x00 << 2)
#define BMK_HID_MAIN_VAL_CONST (0x01 << 0)
#define BMK_HID_MAIN_VAL_ARRAY (0x00 << 1)

static const uint8_t hid_report_map[] = {
    HID_USAGE_PAGE(HID_USAGE_GEN_DESKTOP),
    HID_USAGE(HID_USAGE_GD_KEYBOARD),
    HID_COLLECTION(HID_COLLECTION_APPLICATION),
    HID_REPORT_ID(BMK_HID_REPORT_ID_KEYBOARD),
    HID_USAGE_PAGE(HID_USAGE_KEY),
    HID_USAGE_MIN8(HID_USAGE_KEY_KEYBOARD_LEFTCONTROL),
    HID_USAGE_MAX8(HID_USAGE_KEY_KEYBOARD_RIGHT_GUI),
    HID_LOGICAL_MIN8(0x00),
    HID_LOGICAL_MAX8(0x01),

    HID_REPORT_SIZE(0x01),
    HID_REPORT_COUNT(0x08),
    HID_INPUT(BMK_HID_MAIN_VAL_DATA | BMK_HID_MAIN_VAL_VAR | BMK_HID_MAIN_VAL_ABS),

    HID_USAGE_PAGE(HID_USAGE_KEY),
    HID_REPORT_SIZE(0x08),
    HID_REPORT_COUNT(0x01),
    HID_INPUT(BMK_HID_MAIN_VAL_CONST | BMK_HID_MAIN_VAL_VAR | BMK_HID_MAIN_VAL_ABS),

    HID_USAGE_PAGE(HID_USAGE_LED),
    HID_USAGE_MIN8(HID_USAGE_LED_NUM_LOCK),
    HID_USAGE_MAX8(HID_USAGE_LED_KANA),
    HID_REPORT_SIZE(0x01),
    HID_REPORT_COUNT(0x05),
    HID_OUTPUT(BMK_HID_MAIN_VAL_DATA | BMK_HID_MAIN_VAL_VAR | BMK_HID_MAIN_VAL_ABS),

    HID_USAGE_PAGE(HID_USAGE_LED),
    HID_REPORT_SIZE(0x03),
    HID_REPORT_COUNT(0x01),
    HID_OUTPUT(BMK_HID_MAIN_VAL_CONST | BMK_HID_MAIN_VAL_VAR | BMK_HID_MAIN_VAL_ABS),

    HID_USAGE_PAGE(HID_USAGE_KEY),

    HID_LOGICAL_MIN8(0x00),
    HID_LOGICAL_MAX16(0xFF, 0x00),
    HID_USAGE_MIN8(0x00),
    HID_USAGE_MAX8(0xFF),
    HID_REPORT_SIZE(0x08),
    HID_REPORT_COUNT(0x06),
    HID_INPUT(BMK_HID_MAIN_VAL_DATA | BMK_HID_MAIN_VAL_ARRAY | BMK_HID_MAIN_VAL_ABS),

    HID_END_COLLECTION,

    HID_USAGE_PAGE(HID_USAGE_CONSUMER),
    HID_USAGE(HID_USAGE_CONSUMER_CONSUMER_CONTROL),
    HID_COLLECTION(HID_COLLECTION_APPLICATION),
    HID_REPORT_ID(BMK_HID_REPORT_ID_CONSUMER),
    HID_USAGE_PAGE(HID_USAGE_CONSUMER),

    HID_LOGICAL_MIN8(0x00),
    HID_LOGICAL_MAX16(0xFF, 0x00),
    HID_USAGE_MIN8(0x00),
    HID_USAGE_MAX8(0xFF),
    HID_REPORT_SIZE(0x08),
    HID_REPORT_COUNT(0x06),
    HID_INPUT(BMK_HID_MAIN_VAL_DATA | BMK_HID_MAIN_VAL_ARRAY | BMK_HID_MAIN_VAL_ABS),
    HID_END_COLLECTION,
};
